### ISSUE TITLE
Build process fails when trying to process icon

### ISSUE THREAD

**Issue by afontcu** [wadetandy/vue-svg-icon-loader#1]
Hi! I'm using your loader - which is cool, thanks!- but I ran into an issue regarding build task and uglify:

```
ERROR in 14-c0365cd5946523d8eeec.js from UglifyJs
Unexpected token: punc (() [./node_modules/vue-svg-icon-loader/lib!./node_modules/svg-sprite-loader/lib/loader.js!./frontend/assets/icons/cash.svg:12,0][14-c0365cd5946523d8eeec.js:19,10]

ERROR in 15-c0365cd5946523d8eeec.js from UglifyJs
Unexpected token: punc (() [./node_modules/vue-svg-icon-loader/lib!./node_modules/svg-sprite-loader/lib/loader.js!./frontend/assets/icons/cart.svg:12,0][15-c0365cd5946523d8eeec.js:19,10]

ERROR in 16-c0365cd5946523d8eeec.js from UglifyJs
Unexpected token: punc (() [./node_modules/vue-svg-icon-loader/lib!./node_modules/svg-sprite-loader/lib/loader.js!./frontend/assets/icons/broken.svg:12,0][16-c0365cd5946523d8eeec.js:19,10]
```

I just ran `npm run build` with a pretty default configuration:
```json
"build": "cross-env NODE_ENV=production webpack --progress --hide-modules --config frontend/webpack.config.js",
```

Any idea why this could happen? I tried to isolate the issue (it probably has something to do with Uglify not being able to uglify ES6) but had no luck.

Thanks!

**Comment by wadetandy** [comment]
Sorry I missed the notification for this when you originally posted.  Yeah this is a problem with Uglify + ES6, which isn't supported by the uglify plugin shipped with webpack. Webpack 4.0 will be bundling the newer version of the plugin which uses uglify 3.0, which does support ES6, but you can manually switch to that in the meantime if you need those features.  See the [uglifyjs-webpack-plugin project](https://github.com/webpack-contrib/uglifyjs-webpack-plugin) for details.
